### ISSUE TITLE
problem with Bibiliograhy

### ISSUE THREAD

**Issue by Aapz** [rriley/qu-thesis#1]
Hi dr,
I am using qu-thesis template to complete my dissertation. But unfortunately while execution the order of reference is not proper. How i can arrange the reference in correct order (first cited ref should number as (1)). if i use Plain, ref is alphabetical order. I tried IEEE tran also. but that is also not working.
However, the latex file is really useful,,,,Thank you very much
Aparna

**Comment by rriley** [comment]
I'm not clear what you mean by "correct order".

Right now I think it puts the references in alphabetical order according to first author's last name.  If I'm understanding you, it sounds like you want them placed in order of appearance.  Is that what you want? 

Neither one of those options (alphabetical or by appearance) is correct vs. incorrect, and it looks like the QU thesis spec doesn't mandate one vs. the other.  Double check with your advisor to see if they have a preference or if your discipline does one vs. the other.  I personally prefer alphabetical as I find it makes it easier for others to quickly see if a specific paper is included in your bibliography.

If you need it in by appearance order, it looks like the bibliography styles unsrt or ieeetr should do it.  Let me know how it goes.

**Comment by Aapz** [comment]
yes dr, my supervisors would like to have appearance order. I tried IEEEtran and unsrt reference style. But its not working for me. If I build only one chapter with IEEE tran style , everything is perfect. But, if i build all chapters  together, then the IEEEtran style is not working. Really confused....

**Comment by rriley** [comment]
Both unsrt and ieeetr work great for me to do what you want.  I suspect something else is wrong.  (Your statement "If I build only one chapter with IEEE tran style" tells me that you are doing something you shouldn't be.

In your working .tex file, simply change:
`\bibliographystyle{plain}`
to
`\bibliographystyle{ieeetr}`

Then re-run latex, bibtex, and latex a few more times.

**Comment by Aapz** [comment]
I figure out the problem dr,,,, I have some figures with citation. So when i build the file, the reference of the figure citation appears on top. When i remove the figure reference, everything is perfect with IEEE tran style.
Thank you very much dr....
